version: "3"
services:
  install:
    # user: node
    image: node:18
    volumes:
      - .:/app
    command: bash -c "cd /app && rm -rf node_modules && rm -f package-lock.json && npm i"    
  build: 
    # user: node
    image: node:18
    volumes:
      - .:/app
    command: bash -c "cd /app && npm run build"   
  installTestDapp:
    # user: node
    image: node:18
    volumes:
      - .:/app
    command: bash -c "cd /app/test && rm -rf node_modules && rm -f package-lock.json && npm i"       
  testDapp:
    # user: node
    image: node:18
    ports:
      - "8035:8080"
    volumes:
      - .:/app
    command: bash -c "cd /app/test && npm run test"
  test:
    # user: node
    image: node:18
    volumes:
      - .:/app
    command: bash -c "cd /app && npm run test"                  